### ISSUE TITLE
ReadExpressions

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#11]
Hi,
I am trying to test your SCADA system.
is there a documentation to know, when defining variables how to use ReadExpressions and WriteExpressions.
I want scale the read values by a factor. I tried to use "raw*10+10", *10, '*10' nothing works.
Can you guide me?
Secondly,
Is there a way to have virtual variables (like constant value tags and calculation value tags) e.g Variable3= Variable1*Variable2
Just to add my raw Modbus Variables are float32 type

Hope you can respond soon

**Comment by kimdiego2098** [comment]
The `raw` has been changed to object type, so running ``raw * 10+10`` will result in an error, because the object does not support math. Please change to ``raw.ToInt() * 10+10``

**Comment by kimdiego2098** [comment]
It is not supported to directly define memory variables, but can be performed through other variable values in read and write expressions, such as `` GlobalData.ReadOnlyVariables["OtherVariableName"]. Value.ToInt()+raw. ToInt()*10+10``

**Comment by ajaywazir** [comment]
> The `raw` has been changed to object type, so running `raw * 10+10` will result in an error, because the object does not support math. Please change to `raw.ToInt() * 10+10`'


Thanks.
I tried raw.ToInt() * 10+10 and it works as expected

I need the final value as decimal (single or double)
I tried to use  (decimal)raw* 1.333; as well as Convert.ToDecimal(raw);
Both do not work. Any Ideas?

**Comment by kimdiego2098** [comment]
The expression is  C# from cs-script, so you can write all the operations you need in C#

**Comment by kimdiego2098** [comment]
The project has built-in extension methods, and you can use ``raw.ToDecimal()``

**Comment by ajaywazir** [comment]
Thanks. I will try. However, there is one issue in variable evaluation, Some variable are rounded to zero decimals.
Any  Ideas why?
All vaiables have similar defintions?

![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/55a39de4-884d-4f00-91ba-1346782f1079)
![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/b7047d11-4415-49ae-8aec-e14886704445)

**Comment by kimdiego2098** [comment]
This is a bug in modsim, please use modbusSlave

**Comment by ajaywazir** [comment]
Aha, I see.
Thanks. I will check with another Simulator
I got it running.
Now I need to figure out scaling using raw.ToDecimal() *1,234

**Comment by ajaywazir** [comment]
Thanks for your help

**Comment by ajaywazir** [comment]
> GlobalData.ReadOnlyVariables["OtherVariableName"]. Value.ToInt()+raw. ToInt()*10+10

Hi Bro,
I tested this and it works, within the same device.
For this formula, is it possible to use variable from another device? Is so how?

**Comment by kimdiego2098** [comment]
Of course,  it is only related to variable names and no relation to other devices
