### ISSUE TITLE
Alarm Settings

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#12]
Hi,
Is there a documentation on how to set alarm level values?
For example, I need to set alarm when raw above a certain value OR below a certain value?

Is this something that can work?
![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/3adb983b-a53c-4567-8296-a99a2b2636e7)

**Comment by kimdiego2098** [comment]
Write in the HAlarmCode , such as 10.123

**Comment by ajaywazir** [comment]
Thanks. It works as expected
What is the purpose of  HRestrainExpressions?

**Comment by kimdiego2098** [comment]
Additional constraints
