### ISSUE TITLE
Historising Alarms in QuestDB

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#13]
Hi,
I added QuestDB connection string to SQlHISALM connector
while connection is ok and table is automatically created but there is following error while saving actual data?
Any idea what I could be doing wrong?

Error message:Nuget安装：SqlSugar.QuestDb.RestAPI ，QuestDb中请使用：await db.RestApi().BulkCopyAsync(list) 注意是db.RestApi()不是db.Fastest Exception stack:SqlSugar.SqlSugarException: Nuget安装：SqlSugar.QuestDb.RestAPI ，QuestDb中请使用：await db.RestApi().BulkCopyAsync(list) 注意是db.RestApi()不是db.Fastest at SqlSugar.Check.ExceptionEasy(String enMessage, String cnMessage) at SqlSugar.QuestDBFastBuilder.ExecuteBulkCopyAsync(DataTable dt) at SqlSugar.FastestProvider`1._BulkCopy(List`1 datas) at SqlSugar.FastestProvider`1.<>c__DisplayClass13_0.<<BulkCopyAsync>b__0>d.MoveNext() --- End of stack trace from previous location --- at SqlSugar.ContextMethods.PageEachAsync[T](IEnumerable`1 pageItems, Int32 pageSize, Func`2 action) at SqlSugar.FastestProvider`1.BulkCopyAsync(List`1 datas) at ThingsGateway.Plugin.SqlHisAlarm.SqlHisAlarm.InserableAsync(List`1 dbInserts, CancellationToken cancellationToken)

![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/c4c3aede-4be9-4a09-8cad-271c08ebc99b)
![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/6854edc7-2640-48ea-ad1a-b3f4eb265170)
![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/171f01c2-85dc-4ecc-9155-14ba5709048a)
![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/09cbb329-de7a-4c6f-9d1d-e3d1956a9743)
![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/6ee25aac-bb6c-4977-b099-75a6258488b5)

**Comment by kimdiego2098** [comment]
ok, sqlHisAlarm  QuestDB  Will be supported in version 6.0.3.66 soon

**Comment by ajaywazir** [comment]
> ok, sqlHisAlarm QuestDB Will be supported in version 6.0.3.66 soon

Thanks. The tag historisation also does not work in this scenario.
Hope you can implement both.

Thanks

**Comment by kimdiego2098** [comment]
> > ok, sqlHisAlarm QuestDB Will be supported in version 6.0.3.66 soon
> 
> Thanks. The tag historisation also does not work in this scenario. Hope you can implement both.
> 
> Thanks

Using another plugin for historical data storage, thingsgateway.plugin.questdb
