### ISSUE TITLE
MQTT JSON to Variable

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#14]
Hi,
Is it possible to push data to BackEnd Server (Device/Variables) using MQTT/JSON.
We will set up a business
If yes, what is the JSON structure needed to be?
Is there any example or documentation?

![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/c515f41c-7cc4-47d4-9e10-d9dcc2c527b6)
![image](https://github.com/kimdiego2098/ThingsGateway/assets/17775504/776d56b3-e79c-4c5f-a1a0-deaeb70c7b1f)

Regards
Ajay

**Comment by kimdiego2098** [comment]
docs:  https://kimdiego2098.github.io/docs/


![image](https://github.com/kimdiego2098/ThingsGateway/assets/82756760/88d5d589-816c-40f6-a3cd-4c9248e16a48)

You need to bind the variable to the business plugin, or check IsAllVariable

![image](https://github.com/kimdiego2098/ThingsGateway/assets/82756760/5e9a3489-138f-417f-a36d-daf95c058714)
