### ISSUE TITLE
CSV & MQTT Capture Plugin

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#15]
Do you have plans for having a capture plugin to capture data from external sources
1. Read variables from a CSV file, that can be modified externally by hand or by another automated process?
2. Capture variables from MQTT subscription supplied on a pre-defined JSON format?

**Comment by kimdiego2098** [comment]
no plan, you can consider implementing this plugin yourself, just implement the plugin and call ``VariableRunTime.SetValue`` method updates variable values, and a similar solution is ``ThingsGateway.Plugin.OpcUa``

**Comment by ajaywazir** [comment]
Thanks. Let me start with DLT645 as base. Looks less complex than others.

**Comment by ajaywazir** [comment]
> VariableRunTime.SetValue

So, If I understand correctly, I do not have to implement ReadAsync only WriteAsync.
Is that right?
