### ISSUE TITLE
Adding a new type of Channel

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#16]
Hi,
How to add a new type of channel. I call as FileSystem Channel, that works like TCP or UDP channel but does not make any active connections. 
I have implemented the Constant value plugin that reads data from CSV file, but I am forced to use a TCP type connector and I cannot seem to use a Blank (Other) type channel.
Do you have any suggestions?
I added the following file to ThingsGateway.Foundation.csproj but it does not appear in my Channel options.
[FileSystemSession.zip](https://github.com/user-attachments/files/16162599/FileSystemSession.zip)

Regards
Ajay

**Comment by kimdiego2098** [comment]
通道类型选择other，区别是插件init方法中传入的channel参数为null，这不影响你的实现目的

**Comment by ajaywazir** [comment]
Thanks. Let me try

**Comment by ajaywazir** [comment]
In this case, there will be only a one time read at loading time.
If I use a dummy TCP channel as a channel that enables periodic read and write, I am able to have more interaction with variables.
How can we achieve this with a dummy (other)  type channel?
How to add a new type of channel with no connectivity but timer based read and write

**Comment by kimdiego2098** [comment]
1、public override Init
﻿
In this method, initialize the connections you need, such as CSV file paths, encapsulated objects, etc. This method will only be executed once during the plugin lifecycle
﻿
2、protected override ProtectedExecuteAsync
﻿
In this method, perform the read operation you need, and the method will execute infinitely (serially) throughout its lifecycle. Please note that the interval between each execution is the minimum interval (default is 10ms)
﻿
3、example
﻿
Check the non subscription mode in the ``OPCUAMaster`` plugin, this is the same operation

**Comment by ajaywazir** [comment]
Hi Bro,
Are you planning any plugin for  IEC104 protocol?

Regards,
Ajay

________________________________
