### ISSUE TITLE
Cannot Compile  ThingsGateway.Admin.Application in the  6.0.1.3

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#17]
Cannot compile  Project ThingsGateway.Admin.Application in the  6.0.1.3
![image](https://github.com/user-attachments/assets/dbbed113-f2da-4467-8416-66bfd422b3e3)

**Comment by kimdiego2098** [comment]
Update to the latest version ``6.0.4.28``

Then the error message seems to indicate that you made some changes that caused some code duplication and conflict. Perhaps you should pull the latest Git code and restore your own business code to check for Git changes

**Comment by ajaywazir** [comment]
Thanks. It works now.
What happened to QuestDB producer? You have removed it from latest release?

**Comment by kimdiego2098** [comment]
Oh, it has been merged into the DB assembly plugin
