### ISSUE TITLE
The project ThingsGateway.Foundation.SourceGenerator cannot be compiled

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#19]
Hi 
Using lates source code as on today I am unable to compile this project :  
`ThingsGateway.Foundation.SourceGenerator  `
This results in project 
`ThingsGateway.Foundation.Variable `
also failing to compile.  

I, then, removed the reference to  `ThingsGateway.Foundation.SourceGenerator`  project from   
`ThingsGateway.Foundation.Variable` , then  `ThingsGateway.Foundation.Variable`  can compile.

The error I receive is while compiling `ThingsGateway.Foundation.SourceGenerator` project is as follows:

`Error (active)		Could not find a part of the path 'C:\ThingsGateway-master\src\adapter\ThingsGateway.Foundation.SourceGenerator\obj\Debug\netstandard2.0\ThingsGateway.Foundation.SourceGenerator.GeneratedMSBuildEditorConfig.editorconfig'.	ThingsGateway.Foundation.SourceGenerator (netstandard2.0)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets	191	
`
Any idea why? I am using VS 2022 Community Edition

**Comment by kimdiego2098** [comment]
dotnet/roslyn-analyzers#6632

It looks like this issue
