### ISSUE TITLE
Using Memory Variable

### ISSUE THREAD

**Issue by ajaywazir** [kimdiego2098/ThingsGateway#20]
Hi,
I am trying the new Memory Variable. I have a read expression DateTimeOffset.Now.ToUnixTimeSeconds()
I set device cycle to 10000 and variable cycle to 1.
I was expecting the value of the variable to increase by 10 every 10 seconds. It does not seem so. 
It loads the value one at start up and not after that. It is also updated whenever I write any value to it.

Is this how it is supposed to work?
Regards
Ajay

**Comment by kimdiego2098** [comment]
This should not be in line with the design. I have checked the code and this condition should be removed. It will be updated soon

![image](https://github.com/user-attachments/assets/b3d3384e-9789-4c90-88ee-7673883aa0be)
